### ISSUE TITLE
Safari?

### ISSUE THREAD

**Issue by exside** [allartk/leaflet.offline#1]
Hi,

thanks for your efforts with this project!

Just wanted to ask if you ever tested Safari (8.x) with your code? Seems like the indexDB stuff is failing...looks like Safari cannot store blobs like old chrome...

Error uncatched: [Error] DataCloneError: DOM IDBDatabase Exception 25: The data being stored could not be cloned by the internal structured cloning algorithm.
Error message catched exception: DataCloneError: DOM IDBDatabase Exception 25

**Comment by allartk** [comment]
Thanks! On https://github.com/allartk/leaflet.offline/blob/master/src/Control.SaveTiles.js:127 I wrote a condition for this issue which maybe should be updated. I hope I wil have some time soon to check.
