### ISSUE TITLE
Downloadbutton outside of map

### ISSUE THREAD

**Issue by brotkiste** [allartk/leaflet.offline#10]
Hi,
your plugin looks great :)
I'm planning to integrate it in my leaflet application, but I'd prefer to have the download/delete button in the layercontrol next to the layer selector.
Something like this (not tested):

```
var control = L.control.savetiles(offlineLayer, {
            ...
        });

var baseMaps = {
    "OfflineLayer <button onclick="control._saveTiles()">...</button>": offlineLayer
};
```

Do you think this could be supported by the plugin or do you know a nicer way to do this?

Thanks :)

**Comment by brotkiste** [comment]
If you think that's in the scope of the plugin, I'd also be happy to contribute

**Comment by allartk** [comment]
If i understood correct: You want to hide button at its current position and show elsewhere. 

I say elsewhere because i can imagine there might be wishes to put them even outside the map, controlled by some other library (eg react.) That is my view this is up to the user. But hidding is in scope :)

**Comment by brotkiste** [comment]
Yes :)
I hope to have it look like this in the end (see attachement)
Putting them outside of the map would definitely also make sense.
Which approach would you choose to reach this?

![screenshot from 2017-10-11 18-24-55](https://user-images.githubusercontent.com/1833328/31453322-1002f558-aeb2-11e7-81fe-d47ead82dbd1.png)

**Comment by allartk** [comment]
I had time to look at my own code today :)

For the moment i think you can hide the buttons with default css.
```css
.savetiles { display:none  } 
```

And attach an event listener to your custom controls:

```js
document.getElementById("remove_tiles").addEventListener('click',function(e) {
    control._rmTiles();
});
```
