### ISSUE TITLE
Setting bounds on saveTiles

### ISSUE THREAD

**Issue by brotkiste** [allartk/leaflet.offline#11]
One more question :)
I'm thinking about manually setting the bounds of the downloaded area to the scope off my app. E.g. via options.
This way you only have to download once and you have covered the whole service area of my mountain rescue department.
What do you think about that?
I think I could do a pull-request within next week

**Comment by allartk** [comment]
I would like to read your ideas/ or see the pull request.

**Comment by brotkiste** [comment]
This worked for me, what do you think about it?
I have to admit I underestimated the number of tiles that would have to be downloaded for this.
