### ISSUE TITLE
_getStorageKey is mangling URLs

### ISSUE THREAD

**Issue by disarticulate** [allartk/leaflet.offline#13]
I reviewed the code but can't find the specific.

using cartodb's basemap url:
```
https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
```
The plugin appears to come up with:
```
https://a.rtodb-basemaps-a.global.ssl.fastly.net/light_all/6/56/28.png
```
Not sure how it's doing the mangling.

**Comment by allartk** [comment]
I can confirm, i wrote a test to reproduce. I will try to fix

**Comment by allartk** [comment]
I released a fix

**Comment by disarticulate** [comment]
I'll test it out shortly.
