### ISSUE TITLE
map not updated during saving

### ISSUE THREAD

**Issue by harry-73** [allartk/leaflet.offline#154]
When we are saving tiles, the map does not update on a change of zoom, move.
The area being saved remains but the rest is grey.
The map updates when the saving is finished.

**Comment by allartk** [comment]
Which browser & do you have a code example?

**Comment by harry-73** [comment]
> Which browser & do you have a code example?

I am using Chrome and it is from your example:
![leaflet offline](https://user-images.githubusercontent.com/51455661/157463712-1ed7b2cf-d176-4910-9377-e5546a229ce3.png)

**Comment by allartk** [comment]
Can you check what happens in the dev panel? 

I expect the tiles will be shown, after other tile requests from your download are finished.

**Comment by harry-73** [comment]
Nothing happens in the dev panel. 
Yes, after the download is finished, tte tiles are shown.
I did a test with parrallel option at 1 and now it works. So it seems that the parallel offline downloads are taking the priority regarding the download for the map.

**Comment by harry-73** [comment]
I did some more tests. In fact, it seems that concurrent access to the database is the cause. I submitted a PR to avoid this.

**Comment by allartk** [comment]
Fixed in pr
