### ISSUE TITLE
saveWhatYouSee only current zoom level

### ISSUE THREAD

**Issue by DanielShinken** [allartk/leaflet.offline#17]
Hi there, I'd like to know if there's a way to pass saveWhatYouSee option to save control, but instead of saving the current zoom level, plus deeper zoom leves, I'd like to save only the current zoom level, so if my view of the map is on a low zoom level, I won't start saving thounsands of tiles of the deeper levels, if I move my map zoom to a greather zoom level, let's say 9 -- > 10 I got save tiles from the view I got from level 9 zoom before zooming in, and tiles from level 10 zoom, but just my current bounds of level 10, I hope I made miself clear, and I hope you guys can help me out, thanks.

PD: Awesome plugin btw.

UPDATE: Hey I already accomplished what I was trying to do, I add another option to L.control.savetiles, naming it "saveCurrentZoom" then on _saveTiles function did this 
zoomlevels.push(this._map.getZoom()); and add and zoomend event to my map, inside this event I call control._saveTiles() and that was it, pretty simple actually, thanks for this plugin and sorry for opening an issue for something that simple. Thank you.

**Comment by allartk** [comment]
:+1: 

For future reference: 
Personally, i would use a event listener on [zoomend](http://leafletjs.com/reference-1.3.0.html#map-zoomend) and call
https://github.com/allartk/leaflet.offline/blob/master/docs/api.md#setzoomlevels.
