### ISSUE TITLE
Tiles being saved as undefined

### ISSUE THREAD

**Issue by jabelone** [allartk/leaflet.offline#19]
Hi,

I believe I'm using leaflet.offline correctly but I'm getting weird results. I copy/pasted from the example into my own project. Now all of the functionality appears to work. I can monitor the download progress, see how many tiles are currently saved etc. However, when trying to load the tiles with no internet connection they never load.

I dug into the chrome application tab under developer tools and think I found the reason. (note, the example suffers from the same problem)

The forage section under IndexedDB appears empty, and all the tile entries have undefined in the Value column.
![image](https://user-images.githubusercontent.com/9560876/36405478-02ba652a-1645-11e8-97a3-f6b6df9b8b24.png)
![image](https://user-images.githubusercontent.com/9560876/36405490-202db92c-1645-11e8-8e09-b03875c6a018.png)

Any help would be appreciated, thanks :)

**Comment by allartk** [comment]
Due to #20  i cannot replicate now.
