### ISSUE TITLE
Bad tile urls on zoom levels different from current one

### ISSUE THREAD

**Issue by sebastianquack** [allartk/leaflet.offline#2]
This is really useful!

One thing - I seem to only able to save tiles on the current zoom levels - I'm getting bad tile urls ( leading to 404 errors, for example this one: http://b.tile.osm.org/16/134708/86612.png ) as soon as multiple zoom levels are specified in options.zoomlevels

@allartk have you been seeing this behaviour? Not sure what the cause is.. any help appreciated!

**Comment by allartk** [comment]
I am not aware of this behavior, the example seems to work (http://allartk.github.io/leaflet.offline/) . Can you show me some code, and  tell what version are you using (master, or one of the releases?)

**Comment by sebastianquack** [comment]
when I go to the example, zoom out once and then click on save tiles I get a 404 after 2 tiles - this one http://a.tile.openstreetmap.org/15/33675/21649.png - maybe I don't understand the expected behaviour
![screen shot 2017-02-19 at 11 14 04](https://cloud.githubusercontent.com/assets/3055845/23101479/91757c22-f694-11e6-8498-f3886e951558.png)

**Comment by allartk** [comment]
This is a bug! I will fix asap

**Comment by allartk** [comment]
It is probably solved in the last commits/beta release. I will add some extra test the next days, to be sure.

**Comment by sebastianquack** [comment]
Awesome - works! Thanks for the quick fix
