### ISSUE TITLE
Webworker enable

### ISSUE THREAD

**Issue by rwilliam99** [allartk/leaflet.offline#202]
I love how this has been implemented but I've found one thing that prevents me from using it.  It is unusable for downloading anything more than a couple thousand tiles at a time - it essentially brings the browser to a halt.

I've been learning npm and more advanced javascript stuff and trying to understand in detail how all this works and believe that implementing a webworker to do the tile downloading and saving to idb would resolve this issue.

Any thoughts on that approach?

**Comment by allartk** [comment]
How many tiles is this about?

**Comment by rwilliam99** [comment]
I've been playing with developing an offline map option to be used on my phone when hiking.  The number of tiles would easily be in the 10s of thousands and even hundreds of thousands wouldn't necessarily be out of line given I will be pulling in multiple layers (tilesets).

**Comment by allartk** [comment]
For that use case, I recommend https://github.com/osmandapp/Osmand or similar. It will perform much better.
