### ISSUE TITLE
Upgrade to v3 problem

### ISSUE THREAD

**Issue by jpmc3630** [allartk/leaflet.offline#215]
Hi :)

When I update to the latest version ^3.0.0-rc.1 I'm getting 

```TypeError: L.tileLayer.offline is not a function```

Downgrading to version 2.1.0 solves it again.

I'm using vue 3.

Thanks

**Comment by allartk** [comment]
Hi, at this moment v3 is tested with imports like in https://github.com/allartk/leaflet.offline/blob/develop/docs/src/index.js

**Comment by allartk** [comment]
Please let me know, Did it work? Can I close the ticket?
