### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gchokeen** [allartk/leaflet.offline#216]
We were trying to integrate leaflet offline in ionic/angular, but there were no compatible type definitions. Do you have any article to explain using offline plugin in the ionic/angular. It will be very useful.

**Comment by allartk** [comment]
Which version do you use? The version tagged with next should have ts definitions

**Comment by gchokeen** [comment]
We use  leaflet-offline `2.2.0` and leaflet `1.8.0`

**Comment by allartk** [comment]
Please try the leaflet.offline prerelease, it is rewritten in typescript. See the readme for install instructions.

`npm install leaflet.offline@next`

**Comment by allartk** [comment]
Did it work? Can I close the ticket?

**Comment by gchokeen** [comment]
@allartk  Sorry, I missed your response! 

It's still not working, I'll give what issues we facing 

#Attempt 1:

```
      this.map = L.map(this.mapID, mapOptions);
      tileLayer(query).addTo(this.map);
      const baseLayer = L.tileLayer.offline
        (query, {}, {
          minZoom: 0,
          maxZoom: 9,
        })
      this.map.addLayer(baseLayer);
```

Type Error:  this.map.addLayer(baseLayer);


Argument of type 'TileLayerOffline' is not assignable to parameter of type 'Layer'.
  Type 'TileLayerOffline' is missing the following properties from type 'Layer': addTo, remove, removeFrom, getPane, and 32 more.ts(2345)


#Attempt 2:

```

    const baseLayer = L.tileLayer.offline
      (query, {}, {
        minZoom: 0,
        maxZoom: 9,
      })

      var mapOptions = {

      crs: crs,
      layers: [baseLayer],
      };

       this.map = L.map(this.mapID, mapOptions);
      tileLayer(query).addTo(this.map);

```
No Type error but map is blank because on console we got following error 

ERROR TypeError: leaflet__WEBPACK_IMPORTED_MODULE_2__.tileLayer.offline is not a function


#Attempt 3:

As per your example : https://github.com/allartk/leaflet.offline/blob/master/docs/src/index.js

```
   this.map = L.map(this.mapID, mapOptions);
   tileLayer(query).addTo(this.map);


    const baseLayer = L.tileLayer.offline
    (query, {}, {
        minZoom: 0,
        maxZoom: 9,
    }).addTo(this.map);

```

Type error: Property 'addTo' does not exist on type 'TileLayerOffline'.ts(2339)

It's long standing issue for us, it's stopping us to release app for long time. Will you available for paid job to solve it. You can even just write us simple article or demo ionic/angular app or if you willing you can directly work our project. Please let me know

**Comment by gchokeen** [comment]
I noticed, I was also installed `npm i --save-dev @types/leaflet.offline` and it was different (outdated) from what you have in plugin. so I uninstalled that module and checked, but still types are not deducted. How can I use it ?

**Comment by gchokeen** [comment]
Thanks for reopening, Do you got any solution! we still stuck on this issue

**Comment by gchokeen** [comment]
Hi Allark, I tried to create new ionic project to see any workout, but getting same error. here is the repo with code : https://github.com/gchokeen/leaflet-offline-ionic


const baseLayer = L.tileLayer.offline
        (query, {}, {}).addTo(this.map);


```
 ERROR TypeError: leaflet__WEBPACK_IMPORTED_MODULE_2__.tileLayer.offline is not a function
    at home.page.ts:66:25
    at timer (zone.js:3155:47)
    at _ZoneDelegate.invokeTask (zone.js:443:35)
    at Object.onInvokeTask (core.mjs:26218:33)
    at _ZoneDelegate.invokeTask (zone.js:442:64)
    at Zone.runTask (zone.js:214:51)
    at ZoneTask.invokeTask (zone.js:525:38)
    at ZoneTask.invoke (zone.js:514:52)
    at data.args.<computed> (zone.js:3135:36)
```

**Comment by allartk** [comment]
I just published 3.0.0-rc.2, I hope it partially fix this issue, if you still get some type errors, they might not be exported from the library, so please report back.

**Comment by gchokeen** [comment]
Hi allartk, I got help from someone in the community and helped to solve the typescript issue, he came with solution using existing  @types/leaflet-offline package. Here is his pull request : https://github.com/gchokeen/leaflet-offline-ionic/pull/1

**Comment by allartk** [comment]
I think rc.4 fixes all what I was aware off. Please reopen if not fixed. 

BTW this types package is for version 2.x of this package.
