### ISSUE TITLE
Show offline map for Iran

### ISSUE THREAD

**Issue by uthmanrahimi** [allartk/leaflet.offline#226]
Hi.
First of all, I need to say Thank You for this great repository.
I need to show offline map (Iran), I just wanted to know, does this repository can help? if yes, what should I do?
after all, I need to show some markers on the map, for example User enter Lat and Long on for each Asset and I should show them on the map.

**Comment by allartk** [comment]
This library is helpful for smaller areas, inside a browser (or webapp with cordova). For a complete country, i would advice other solutions, on mobile phone some app, on desktop a gis viewer such as qgis.
