### ISSUE TITLE
Loads 'undefined' when added to map. Multiple baselayer support?

### ISSUE THREAD

**Issue by ansonl** [allartk/leaflet.offline#23]
When using tilelayer.offline and adding it to a map. The leaflet offline script will make a call to load "/undefined" resource. 
This can be tested by loading the example site and seeing the network request for http://allartk.github.io/leaflet.offline/undefined. 

Should there be anything at this path?

Also, when I save some tiles on a base layer and recreate the Save/Remove controls for a new base layer with L.control.savetiles(baseLayer, {...}), a JS error saying the function is not a callback is thrown. Is there an additional step to working with multiple base layers? Thanks.

**Comment by allartk** [comment]
For undefined: the cdn used should be updated

For multiple baselayers, have a look at https://github.com/allartk/leaflet.offline/blob/master/docs/api.md#setlayer
