### ISSUE TITLE
index.js:362 Uncaught TypeError: L.control.savetiles is not a function

### ISSUE THREAD

**Issue by v-ngangarapu** [allartk/leaflet.offline#232]
Hi,
 On loading the application, script not able find the L.control.savetiles function. 

I am using the package version - "leaflet.offline": "3.0.0-rc.2"

I tried with package version - "leaflet.offline": "3.0.0-rc.1", script not able to find the L.tileLayer.offline function. This issue got resolved in "3.0.0-rc.2".

I am testing this on windows 11 Enterprise.

Any suggestions here.

![image](https://user-images.githubusercontent.com/82965480/198489375-22452e75-92dc-40b6-8c6e-e921861baa7f.png)

**Comment by v-ngangarapu** [comment]
I don't see this issue with v2.2.0

**Comment by allartk** [comment]
Thank you for reporting, when i have time i will fix it and publish rc3

**Comment by allartk** [comment]
Hi, rc.4 should fix, please reopen if not!
