### ISSUE TITLE
is Node 16 really required?

### ISSUE THREAD

**Issue by VashJuan** [allartk/leaflet.offline#245]
Using leaflet.offline@3.0.0-rc.2 I get the following error:

PS D:\Projects\RangerTrak\rangertrak> npm update @types/jasmine rxjs
Debugger listening on ws://127.0.0.1:63433/3a9f1f51-b56a-4201-a4b4-ce17a2de028b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
**npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'leaflet.offline@3.0.0-rc.2',
npm WARN EBADENGINE   required: { node: '16.x' },
npm WARN EBADENGINE   current: { node: 'v19.0.1', npm: '9.1.2' }
npm WARN EBADENGINE }**

Is the restriction on node 16 intentional, or can it be loosened up?!

**Comment by allartk** [comment]
Seems #237 , please update to rc.4

**Comment by VashJuan** [comment]
Ooops, sorry.
