### ISSUE TITLE
Move to a more permissive License

### ISSUE THREAD

**Issue by TekSiDoT** [allartk/leaflet.offline#26]
To be honest, the GPL seems like an odd choice considering the rest of the Leaflet environment mostly uses MIT / Appache Licenses. Many companies also do not consider using GPL licenses due to legal uncertainties. Any chance you would consider changing the license?

**Comment by allartk** [comment]
I wrote most of this code in my free time, MIT is very permissive. I would like to keep the software public.
 On the other hand, GPL is very restrictive. Would LGPL be ok for you? 

In this case, i have to contact all contributors, which can take some time..

**Comment by TekSiDoT** [comment]
Thanks for considering a license change, I think LGPL would be a great fit for the purpose and the application of your library.

I hope all your contributors agree that this license change is actually for the benefit and proliferation of the lib.

**Comment by allartk** [comment]
@brotkiste  @robertomlsoares  @slurmulon @bmcbride  

We would like to move to LGPL. Could you give us permission?

**Comment by brotkiste** [comment]
sure :)

**Comment by allartk** [comment]
@slurmulon @bmcbride  Can you give your response? Thank you.

**Comment by bmcbride** [comment]
You have my permission to change the license!

**Comment by allartk** [comment]
i updated the license!
