### ISSUE TITLE
Programmatic Use without displaying actual control on the map

### ISSUE THREAD

**Issue by ohenepee** [allartk/leaflet.offline#29]
Is there a way to use this control programmatically? I find it tedious to have user having to click the save button for who know how many times.

**Comment by cieralteir-halcyon** [comment]
You can call the _saveTiles method from the ControlSaveTiles manually.
`
let control = L.control.savetiles(layer, options);
control._saveTiles();
`

**Comment by allartk** [comment]
In version 2 this will be easier

Functions to control the storage are in a seperate component.
https://github.com/allartk/leaflet.offline/blob/TileManager/src/TileManager.js 
These functions will be exported to use directly.
https://github.com/allartk/leaflet.offline/blob/TileManager/src/index.js
