### ISSUE TITLE
Function confirming the removal of tiles.

### ISSUE THREAD

**Issue by robertomlsoares** [allartk/leaflet.offline#3]
Hi, I started using this lib for a project and some features would be easier to add in its source code instead of hacking my code so I don't need to alter the code from libraries. For example I need a confirmation that the user wants to delete all the tiles (it shouldn't be too hard). Is that something that interests you? I can send pull requests if you'd like help with it.

**Comment by allartk** [comment]
Hi, a pull request for the delete confirmation is welcome! I suggest: Something comparable with what is done for the save confirmation.
