### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by philipgriffin** [allartk/leaflet.offline#31]
Hey this project is really cool! Thanks for working on it!

I was wondering if it is possible to have a concept of multiple maps with this implementation. 

What I mean by that is presume you have a hiking application with two different suggested hikes.

You save the map for 'hike A' and then save the map for 'hike B' then you could individually remove the tiles meant for 'hike A' or 'hike B' or else just prompt the storage to load only the tiles for 'hike A'.

I hope this makes sense.

Thanks

**Comment by allartk** [comment]
You have to create this logic yourself.

In version 2 you could use the getStorageInfo to get meta info (such as x,y,z) of the stored tiles, which should make it easier to implement.
