### ISSUE TITLE
npm 1.0.4 needs to be rebuilt

### ISSUE THREAD

**Issue by kaxline** [allartk/leaflet.offline#32]
Hi there, I think the `bundle.js` that's currently in the npm 1.0.4 package does not have the latest changes in it. The `src` is all current, so I think you just need to run `npm build` and then `npm publish` to get the `dist/bundle.js` up to date.

I ended up forking the package to add an option that limits the maximum number of tiles that's stored locally, but I also had to rebuild before that just to get the latest commit.

Thanks for this awesome library! Let me know if you have any questions about my issue.

**Comment by allartk** [comment]
I downloaded the package with `npm pack leaflet.offline`. 
The contents of bundles.je seem equal to  https://github.com/allartk/leaflet.offline/blob/v1.0.4/dist/bundle.js 

Which changes do you miss?

Or are you actually asking to build a new version with the latest changes?
