### ISSUE TITLE
Option to generate cache in advance

### ISSUE THREAD

**Issue by piranna** [allartk/leaflet.offline#356]
Add an option to generate the cache in advance (ideally a Node.js cli tool), so later in can be imported on the clients. My idea is to get the map tiles and have them ready, so later the clients can import this package and we ready to navegate offline.

**Comment by allartk** [comment]
Thanks for the suggestion. You're welcome to contribute

**Comment by piranna** [comment]
Well, the fact is that It would need a refactor, exporting some internal references, so somebody with more knowledhe of the codebase could do It better.
