### ISSUE TITLE
How to run it offline?

### ISSUE THREAD

**Issue by vogtmh** [allartk/leaflet.offline#389]
Hi guys, 

nice work, the examples are really impressive and I cannot wait to get it run myself - which is an issue.

I downloaded all the code, loaded the local index.html into my browser and it seems to work. But it cannot download any tiles and I guess it's connected to the error message in the logs: "WebSocketClient.js:21 WebSocket connection to 'ws://0.0.0.0:9000/ws' failed:"

So I'm not sure what went wrong here. I don't want to run the page on a server using docker (as suggested in the docs) and I don't want to setup anything using NPM. I'm just looking for a simple example that works locally. The idea is to have all html, css and js files in a folder on my phone and just open them through the browser. Otherwise, what would be the point of downloading maptiles if the app itself needs to run online. 

Maybe you can just point me to a simple example (maybe a zip file) that I can download and run.

**Comment by allartk** [comment]
Hi,

The software is a library, The examples show an example of how you can implement it in your own website. Not how to build one yourself.

You can view the html generated by the jekyll sources in the repo's docs folder in the example website. For instructions how to transform the source to the html you see online, the jekyll docs have an excelent tutorial
