### ISSUE TITLE
Save zoom based on what you see and deeper.

### ISSUE THREAD

**Issue by robertomlsoares** [allartk/leaflet.offline#4]
Hi!
So, the way it is now, the tiles are saved based on the zoomLevels parameter that you pass for the control. I would like to do it more dynamic instead of hardcoding the zoom levels. For example, the user goes to the place and zooms out and clicks save. Then the layer would save the zoom that he is at at the moment + deeper zooms based on a maxZoom parameter (or a max one that we determine if maxZoom is not provided).
Do you want a pull request for that also? Or should I leave that feature only in my fork? I'm not sure if I like the idea of passing the zoomLevels array to determine what you're gonna save because it's not really what the user sees.

**Comment by allartk** [comment]
It is very good to make it more dynamic, it seems reasonable behave the way you describe by default.  Pull requests are very welcome of course. 

Two functional notes: There should be something to stop the user from saving the world, and i would like backward compatibility.

**Comment by robertomlsoares** [comment]
Yes, I was thinking a parameter called something like saveWhatYouSee (or a better name if you have suggestions) that if it's true then it ignores the zoomLevels array (even if it's provided) and saves based on what I described. Backward compatibility is achieved by not providing saveWhatYouSee (default false) or making it false.

Any ideas on how to stop the user from saving the world? Even now if I put all zoom levels on the zoomLevels array, I could save the world, couldn't I?
I guess one way to do it would be to put a minimum zoom that you can't save below that, for example, 5.
