### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by samuelvanderwaal** [allartk/leaflet.offline#42]
When installed via npm and imported in my main.js file I get the following error upon compiling the project:

```
Error Failed to compile with 1 errors
This dependency was not found:
* leaflet.offline in ./src/main.js
To install it, you can run: npm install --save leaflet.offline
```

Steps to duplicate:

* Set up a new Vue project with [Vue Cli](https://cli.vuejs.org/): `vue create NEW_PROJ` 
* Choose manual configuration and add PWA support
* Install dependencies: `npm install leaflet idb`
* Install library: `npm install leaflet.offline`
* Verify installed modules are present in `node_modules`
* Import library in `main.js`: `import 'leaflet.offline'`
* Compile project with `npm run serve`

**Comment by allartk** [comment]
Could you test again with version 1.0.6, just published

**Comment by samuelvanderwaal** [comment]
The `dist` folder now shows up in the project directory under node modules and building works again, thanks!
