### ISSUE TITLE
TileManager.js Missing from NPM Package

### ISSUE THREAD

**Issue by samuelvanderwaal** [allartk/leaflet.offline#43]
Is TileManager supposed to be included in the package? It's in the source on the master branch and its methods are referenced in the github pages example but it doesn't actually show up in the NPM package. 

Steps to replicate the issue:

Install the library and inspect the src files and `bundle.js`.

And/Or:

Inspect the npm tarball itself using a tool such as [list-npm-contents](https://www.npmjs.com/package/list-npm-contents).

This is the list of all the files in the latest package version:
package.json
.eslintrc.js
.travis.yml
documentation.yml
index.html
karma.conf.js
LICENSE
README.md
rollup.config.js
dist/bundle.js
docs/api.md
src/ControlSaveTiles.js
src/images/save.png
src/index.js
src/localforage.js
src/TileLayerOffline.js
test/SaveTilesTest.js
test/TileLayerTest.js

**Comment by allartk** [comment]
The master branch is version 2, which is not published on npm yet.  I want to check the code and update the documentation (eg events are missing in the generated output) before publishing.

I might consider the publish a beta in the next weeks.

Atm the published version is 1.x
