### ISSUE TITLE
load event fired to often

### ISSUE THREAD

**Issue by Eschon** [allartk/leaflet.offline#51]
I've recently started to make our maps work offline and this plugin has been a huge help.
But I've noticed a small Problem. We use the 'load' event in the Tilelayer that is supposed to fire when all the tiles in view are loaded.

Before switching to your plugin the event was fired exactly once on loading the map before any zooming or panning happens. Now after the switch the event fires about 30 times.

I've seen that this plugin has a 'loadend' event but as far as I can tell this only fires when downloading tiles with the SaveTiles control.

**Comment by Eschon** [comment]
Ok, I did a bit of debugging and digging around in the code and I believe I've found the source of the issue.

In the createTile method the createTile from the L.TileLayer is called to create the tile object. This sets the src and adds event listeners. Then the src is set to an empty string wich causes the load event to fire immediately for all tiles when they are added to the DOM. This causes the first fire of the 'load' event before anything is really loaded.

After that the setDataUrl is called for each Tile where the done handler is called again when the promise either resolves or rejects. Which causes another firing of the 'load' event.

If the promise rejects the src is set back to the image url and the done callback is called immediately which is also not correct since it should only fire once the image is loaded.

I see two ways to resolve those issues:

1) Don't call the createTile method from L.TileLayer and implement the creating of the tile in TileLayerOffline method

2) Prevent the eventhanlders in L.TileLayer.prototype.createTile from being set or remove them before adding the tile to the DOM

I'm not sure which way is best. I guess the method from L.TileLayer is called to ensure that everything needed by leaflet is done and if they later change something about how the tiles work a correct tile is created still. So if we remove the call the plugin might break with future leaflet versions. But removing or preventing the eventhandlers also seems a bit hacky to me.

I would be willing to create a pull request with either solution if you tell me which one you would prefer.

**Comment by allartk** [comment]
Clear and good description, which makes me having the same consideration. 
Since both options are a bit hacky, I want to investigate a bit, eg if we can alter the logic or props used in https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L913
Feel free to remind me if i get silent :)

**Comment by Eschon** [comment]
Thanks for your answer and for taking your time to look into this.
Depending on how long it takes you to check this I might still temporarily create my own fork with a fix since we plan to ship a new version of our app with offline capabilities soon(ish) and we have a screenshotting tool that relies on the load event

**Comment by Eschon** [comment]
@allartk as I mentioned we will release the new version of our app soon so I made a fork with a fix. It is pretty simple, instead of removing the event handlers from the tile I just passed an empty function and set my own event handlers when the tile is not available offline and the src is set.

You can look at it here: https://github.com/Intermaps/leaflet.offline/blob/0f0ec80e9bd5c2736e61ecf6f69329e7ba6840c0/src/TileLayerOffline.js#L29

If that fix is ok for you I could also create a pull request.

**Comment by allartk** [comment]
Yes, it looks good and efficient, if you make a pr i will merge asap.

**Comment by Eschon** [comment]
Thanks I've created the pull request
