### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ThomasCobban** [allartk/leaflet.offline#54]
Hi. This is the first time I've posted an issue so apologies if its a silly one. I've been attempting to integrate the plugin into my website maps, however I seem to encounter a CORS issue at the GET tiles step. My data is stored in an AWS bucket, which has a CORS * policy, allowing access. The JS loads the tiles correctly for viewing however when saving I get the following error:
Access to XMLHttpRequest at 'FILE PATH' from origin 'https://bathymaps.com.au' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. My website htaccess file allows CORS, so I'm assuming its something to do with the way the JS requests to GET the tiles from the bucket? Any help would be great.

**Comment by allartk** [comment]
I recommend opening the browser debug tools and see in eg the network tab which exact url is blocked and check the headers send from this url.

It seems not related to this library, please reopen if it is.
