### ISSUE TITLE
leaflet dependency vs peerDependency

### ISSUE THREAD

**Issue by Eschon** [allartk/leaflet.offline#58]
I just tried updating `leaflet` to the new version 1.7.1 in one of my projects that also uses `leaflet.offline` and the project just stopped working because `L.tileLayer.offline` was undefined. After looking around for a bit I noticed, that while my project was now using leaflet 1.7.1, leaflet.offline was still importing a separate version of leaflet 1.6.0

I'm using `yarn` as a package manager (not sure if it also happens with `npm`) and I was finally able to resolve it by just throwing away my `yarn.lock` and doing a fresh install.

I don't have much experience with maintaining packages, but I think `leaflet.offline` being a plugin for `leaflet` would be a good case for `leaflet` being a peerDependency rather than a normal dependency of the package.

Or is there any reason why it needs to be a direct dependency?

**Comment by allartk** [comment]
I agree :) Another library i maintain already uses peerDependencies. I hope to fix it here soon too.

**Comment by Eschon** [comment]
Thanks! It's not a big deal since it is pretty easy to work around but changing it looks like a cleaner solution
