### ISSUE TITLE
Use in TypeScript Angular 

### ISSUE THREAD

**Issue by BETOXL** [allartk/leaflet.offline#66]
I'm trying to use this library in ionic with Angular but I can't get it to work.
I install as follows
- npm install leaflet --save
- npm install @types/leaflet
- npm install idb --save
- npm install leaflet.offline --save

Inside my .ts file I import it
`import { Map, latLng, tileLayer, Layer, marker, icon } from 'leaflet';`
`import { TileLayerOffline } from 'leaflet.offline';`
```
@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {
  mapL: L.Map;
  baseLayer: TileLayerOffline;
  constructor()
  { }
initLeaflet() {
     // In setView add latLng and zoom
    this.mapL = new Map('mapId');
    this.baseLayer = new TileLayerOffline('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'LOO ©',
    }).addTo(this.mapL);
}
```

**Comment by allartk** [comment]
I've seen already some typescript requests, so I think it does not work with it. 
I would welcome a PR to make it work with typescript.

**Comment by allartk** [comment]
#65

**Comment by BETOXL** [comment]
It would be necessary to create an npm install @types/leaflet.offline
The index.d.ts file is stored in the project in directory: node-modules/@types/leaflet-offline
Its contents:
`
import * as L from 'leaflet';
import * as LO from 'leaflet-offline';
declare module 'leaflet' {
  export class TileLayerOffline {
    constructor(urlTemplate: string, tilesDb: Object, options?: L.TileLayerOptions);
    initialize(url: String, tilesDb: Object, options: Object): void;
    createTile(coords: Object, done: Function): HTMLElement;
    getTileUrl(coords: Object): String;
    getTileUrls(bounds: Object, zoom: Number): Array<any>;
  }
  export function tileLayer(urlTemplate: string, options?: L.TileLayerOptions): L.TileLayer;
  export namespace tileLayer {
    function offline(url: String, tilesDb: Object, options: Object): TileLayerOffline;
  }
  export class ControlOffline {
    constructor(baseLayer: Object, tilesDb: Object, options: Object);
    initialize (baseLayer: Object, tilesDb: Object, options: Object): void;
    onAdd(map: Object): HTMLElement;
  }
  export function control();
  export namespace control {
    export function offline(baseLayer: Object, tilesDb: Object, options: Object):      ControlOffline;
  }
} `

something like that could work I'm going to try it

**Comment by BETOXL** [comment]
I finished assembling the npm type https://www.npmjs.com/package/@types/leaflet-offline, I decided to do it in this project which is a fork of this one, because it allows managing the local storage

**Comment by allartk** [comment]
See #145

**Comment by BETOXL** [comment]
Hello new  [npm ngx.leaflet.offline](https://www.npmjs.com/package/ngx.leaflet.offline) example use Angular  [angular example](https://github.com/BETOXL/offlinemap-angular-example)

**Comment by allartk** [comment]
I will check it later, thanks!
