### ISSUE TITLE
permanent cache for tiles

### ISSUE THREAD

**Issue by rafinewman** [allartk/leaflet.offline#74]
hi,

i tested the demo and found that when closing the browser all downloaded tiles  are gone

how can i download tiles and keep them in browser local storage between sessions (permanent until refreshed by the user)

**Comment by Eschon** [comment]
Hi, this library uses indexedDB to store the tiles so they should be saved between sessions.

Are you sure you are downloading the tiles? The offline Tilelayer does not store them automatically. You have to either use the [ControlSaveTiles](https://github.com/allartk/leaflet.offline/blob/master/docs/api.md#ControlSaveTiles) or trigger storing programatically.
