### ISSUE TITLE
Saving WMS or ESRI tiles

### ISSUE THREAD

**Issue by bdk0172** [allartk/leaflet.offline#76]
We use Leaflet to display a base map using Here Map tiles and then display our customer's own map data as overlays.  That data is either WMS or ESRI which we display using the ESRI Leaflet plugin.  Is it possible to save these tiles for offline display along with the base map tiles?

**Comment by allartk** [comment]
Can you provide a code example of your wish? I am not familiar with the ESRI Leaflet plugin.

Currently only XYZ layers are in scope of this plugin, if you wish to make other services available offline, please write a PR.

Propably you need to add a function to calculate the tile url (see https://github.com/allartk/leaflet.offline/blob/7553a458808fcf238184f1b1ef8d0248cfe89cee/src/TileManager.js#L114).
