### ISSUE TITLE
saveTile is not a function 

### ISSUE THREAD

**Issue by viacheslavspasibo** [allartk/leaflet.offline#79]
Hi there, 

I get the following error when I try to call the saveTile function:

core.js:1449 ERROR Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_2_leaflet_offline__.saveTile is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_2_leaflet_offline__.saveTile is not a function

it's ionic-angular project. 

I imported the modules correctly, since getStorageInfo function works fine without any errors...

help please

**Comment by allartk** [comment]
I asume it is related to version https://github.com/allartk/leaflet.offline/blob/master/src/index.js

**Comment by allartk** [comment]
293e60e47428bafd71e4f381eb67ce1131d29fb8
