### ISSUE TITLE
Question about performance when saving tiles

### ISSUE THREAD

**Issue by robertomlsoares** [allartk/leaflet.offline#8]
Hello!
Do you remember why is that for necessary?

https://github.com/allartk/leaflet.offline/blob/e4eefac03e07754b7ba4724a9bf78b9ed0f92c4b/src/Control.SaveTiles.js#L120-L122

**Comment by allartk** [comment]
It was written to speed up download. subdlength is the number of simaltaneous downloads. 
By default it equals the number of used subdomains. It speeds up download time 3x because 3 subdomains.
