### ISSUE TITLE
savetiles without L.control

### ISSUE THREAD

**Issue by FrancoisTaisne** [allartk/leaflet.offline#84]
well done for all this work.
I would like to be able to save the tiles without button directly when opening the map, without clicking (without L.control).
it's possible ?
Thank you.

**Comment by allartk** [comment]
Steps
* Calculate tile urls you need, https://github.com/allartk/leaflet.offline/blob/v2/docs/api.md#module_TileManager.getTileUrls Use leaflet methods to get zoom & bounds
* For each tile call [https://github.com/allartk/leaflet.offline/blob/v2/docs/api.md#tilemanagerdownloadtiletileurl--promiseblob](downloadTile)
* When the promise resolves, call [https://github.com/allartk/leaflet.offline/blob/v2/docs/api.md#tilemanagersavetiletileinfo-blob--promise](saveTile)

**Comment by allartk** [comment]
you'll need to update to 2.0.1
