### ISSUE TITLE
Saving tiles and share

### ISSUE THREAD

**Issue by hellracer** [allartk/leaflet.offline#9]
Hi,

First of all this is a great project and it works as advertise, the question is can you save specific tiles on specific zoom then save it then distribute this as part of the application? I'm planning to create hybrid up and wrap it with cordova (Offline Map Navigation)?

**Comment by allartk** [comment]
This is out of scope. 
But i would start to have a look at https://github.com/thgreasi/localForage-cordovaSQLiteDriver and https://github.com/litehelpers/cordova-sqlite-ext 

If you need extension of this library to work with cordova components (like thos in the link) i am happy to make changes.
